### ISSUE TITLE
Call `$` as both method and constructor

### ISSUE THREAD

**Issue by Atmos4** [dciccale/ki.js#28]
You can get entirely rid of `i` by calling `$` as constructor. Is this something you have considered?
From my testing, we can shave off ~20bytes by doing this. At the cost of having a method do a lot of things at once, but if it's supposed to be the smallest it can possibly be, then it's worth it?

Also, why is there a final semicolon in the minified version? I am assuming uglify didn't remove it, that's one extra byte!

Side note: I think your gzip sizes are completely wrong. When I run `gzip -c9 ki.min.js | wc -c` without comment, I get 318 bytes. Can you double-check?

Either way, I am a big fan of the project <3

**Comment by dciccale** [comment]
I haven't considered getting rid of i. i think there was still something holding me back trying to get lowest bytes possible but still maintaining it human friendly. because one can go real crazy when putting byte saving first. but we can try it.

reg. gzip, is probably outdated, also you should strip the comments out, anyway i'm getting 308

thanks for your nice words and the support here

**Comment by Atmos4** [comment]
I ended up creating a separate project to dump all my ideas: https://github.com/Atmos4/q.js

If you agree, the plan is to merge as many ideas as possible in your repo as well! :) feel free to take a look and tell me if you like the tooling.

**Comment by dciccale** [comment]
I saw it already, very cool. the code itself for q.js, looks very neat. very similar to ki but better.

I also have used bun for a few things, and i like the additional speed and having build, pacakage manager, etc all included.

the only point i would make here is adoption if there are other contributors, given that i think node+npm is still the most used stack. but there aren't many anyway XD

I don't think there's need for Bun server though? since you could just open the html file that loads the script for testing.

as a note: you should also check out https://github.com/james2doyle/ki.extend.js aslo from a long time ago, someone built really extensive plugin modules adding a ton of features to ki as extensions, we would probably check we don't break those or update them in that case

**Comment by Atmos4** [comment]
Yes that is true! I think the changes I have done so far do not break anything as they don't really change any of the API's core functionality

**Comment by Atmos4** [comment]
I published a PR to solve this: #33
